#!/usr/bin/env bash
g++ main.cpp src/helping_functions.cpp src/classes.cpp src/Entity.cpp src/Player.cpp src/Animation.cpp src/Asteroid.cpp src/Bullet.cpp src/Bomb.cpp -o game -std=c++11 -lsfml-graphics -lsfml-window -lsfml-system
